global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus se monitorea a si mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Metricas de las instancias de API (OpenTelemetry)
  - job_name: 'todo-api'
    static_configs:
      - targets: ['api-1:9464', 'api-2:9464']
    relabel_configs:
      - source_labels: [__address__]
        regex: 'api-(\d+):.*'
        target_label: instance
        replacement: '$1'

  # Metricas de contenedores (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Metricas de Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
