global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus se monitorea a si mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['todo-prometheus.onrender.com']
    scheme: https

  # Metricas de las instancias de API (OpenTelemetry)
  - job_name: 'todo-api'
    static_configs:
      - targets: ['todo-api-latest-gpya.onrender.com']
    scheme: https

  # Metricas de contenedores (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['todo-cadvisor.onrender.com']
    scheme: https

  # Nota: Redis no tiene metricas locales (usando Upstash cloud)
